name: $(Date:yyyyMMdd).$(Rev:r)

parameters:
  - name: buildId
    displayName: 'Build ID (leave empty to use latest)'
    type: string
    default: ''

variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    stages:
      - stage: Release
        jobs:
          - job: Job
            displayName: Release VSCode-Gradle-Nightly
            templateContext:
              type: releaseJob
              isProduction: true
            steps:
              - task: DownloadPipelineArtifact@1
                displayName: Download Pipeline Artifact
                inputs:
                  buildType: specific
                  project: '$(ProjectId)'
                  pipeline: 13344
                  runVersion: latest
                  artifactName: extension
                  targetPath: '$(Build.SourcesDirectory)'
              - task: UseNode@1
                displayName: 'Use Node.js 20.x'
                inputs:
                  version: '20.x'
              - bash: 'npm install -g @vscode/vsce'
                displayName: 'Bash Script'

              - task: AzureCLI@2
                displayName: 'Azure CLI '
                inputs:
                  azureSubscription: 'VSCode-Ext-Publishing'
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: npx @vscode/vsce@latest publish -i '$(Build.SourcesDirectory)/extension/extension.vsix' --manifestPath '$(Build.SourcesDirectory)/extension/extension.manifest' --signaturePath '$(Build.SourcesDirectory)/extension/extension.signature.p7s' --azure-credential

